### PR TITLE
[WIP] Add U2F support

### PR DESCRIPTION
**Pull request by dave-tucker**
This commit adds support for MFA using a U2F device (e.g Yubikey).

Tested and working on Windows.
Example usage:

```
 $ .\aws-okta.exe add
Okta organization: docker

Okta region ([us], emea, preview):

Okta domain [docker.okta.com]:

Okta username: foo@docker.com

Okta password:

time="2019-06-23T20:03:29+01:00" level=info msg="Requesting MFA. Please complete two-factor authentication with your second device"
Touch the flashing U2F device to authenticate...
time="2019-06-23T20:03:33+01:00" level=info msg="Added credentials for user foo@docker.com"
```

```
 $ .\aws-okta.exe login foo
time="2019-06-23T19:59:53+01:00" level=info msg="Requesting MFA. Please complete two-factor authentication with your second device"
Touch the flashing U2F device to authenticate...
```

### CODE REVIEW

**Comment by nickatsegment** [comment]
Thanks for the contribution!

Looks like a lot of copy-paste from the Duo U2F code. Any way we can factor this out?

**Comment by dave-tucker** [comment]
Ignore that last commit - it's not working since my refactoring

**Comment by dave-tucker** [comment]
Ok so the refactor *seems* fine, but it seems that on Windows 10 1903 18362.175 the hid library is no longer able to find my YubiKey 😡 
I'm going to try and root cause this over the next week or so and then hopefully I can actually test it!

**Comment by nickatsegment** [comment]
Closing due to staleness. Ping me if you get to updating.

**Pull request closed without merging**
