### PR TITLE
Update AWS Go SDK To v1.25.35

### PR DESCRIPTION
**Pull request by Tensho**
I'd expect `aws-okta` tolerates [STS regional endpoint](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html) feature. For some reason, [this configuration setting](https://github.com/segmentio/aws-okta/blob/master/lib/okta.go#L267) doesn't work with the current AWS Go SDK version – v1.25.25. Empirically, I have established that AWS Go SDK v1.25.35 fixes this issue.

### Sample Application

```go
package main

import (
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/endpoints"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/sts"
)

func main() {
	conf := &aws.Config{
		Region: aws.String("us-east-1"),
		STSRegionalEndpoint: endpoints.RegionalSTSEndpoint,
	}
	conf.WithLogLevel(aws.LogDebugWithHTTPBody)

	sess := session.Must(session.NewSession(conf))
	svc := sts.New(sess)

	_, err := svc.GetCallerIdentity(&sts.GetCallerIdentityInput{})
	if err != nil {
		fmt.Fprintf(os.Stderr,"STS GetCallerIdentity API call failed: %s", err)
	}
}
```

### Expected Behaviour

`aws-go-sdk: v1.25.35 - current`

```
$ go run main.go
2020/12/14 16:35:22 DEBUG: Request sts/GetCallerIdentity Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.us-east-1.amazonaws.com
```

### Actual Behaviour

`aws-go-sdk: v1.25.25 - v1.25.35`

```
$ go run main.go
2020/12/14 16:35:22 DEBUG: Request sts/GetCallerIdentity Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.amazonaws.com
```

### Considerations

I've updated AWS Go SDK conservatively. We may bump `aws-go-sdk` to the latest version if there are no breaking changes present.

### CODE REVIEW

**Review by nickatsegment — APPROVED** [review]
Sweet, thank you.

**Comment by nickatsegment** [comment]
There's no real good way to test this thoroughly without getting in front of people. Let's do it. If it breaks, I'll revert.

**Comment by Tensho** [comment]
@nickatsegment Would you mind releasing it to homebrew?

**Comment by nickatsegment** [comment]
@Tensho that's up to the community :)

**Pull request merged**
