### PR TITLE
Migrate CircleCI config to 2.0 format

### PR DESCRIPTION
**Pull request by sgerrand**
💁 These changes migrate the existing CircleCI configuration to [2.0 format](https://circleci.com/docs/2.0/).

### CODE REVIEW

**Comment by sgerrand** [comment]
👋 @boggsboggs Would you please review these changes. The CI build is failing because my fork does not have access to the main environment variables.

**Comment by sgerrand** [comment]
🙋 @dfuentes @nickatsegment @systemizer: Are you able to review these changes?

**Comment by nickatsegment** [comment]
@sgerrand thanks for your contribution! I'll take a look today.

**Comment by sgerrand** [comment]
Bugger, you're right. Apologies. I'll add that back in.

**Comment by sgerrand** [comment]
> the deployment step that we used to have

♻️ I've reinstated it in 5a2d75cfacea8122f59477809787b2dcfb5d1090.

**Comment by nickatsegment** [comment]
@sgerrand I've incorporated your work into https://github.com/segmentio/aws-okta/pull/75 and intend to get it merged today. After fiddling with it a bit, I realized there were lots of problems with the old build process and basically rewrote it from scratch. So I'm going to close this PR and prefer that one. Thanks so much for getting this started; it's a lot easier to fix a bug if there's a PR attached :)

**Pull request closed without merging**
