### PR TITLE
Add STS Regional Endpoint Support To Other STS Clients

### PR DESCRIPTION
**Pull request by Tensho**
Follow up to #307.

STS clients are created in multiple places with the lack of STS regional endpoint configuration. The required option was added to all of them. Also, I've tested the entire workflow with `aws-okta exec` command call + enabled HTTP request to debug logging and now everything looks good:
```
...
DEBU[0006] Step 4: Assume Role with SAML
DEBU[0006] Using region: us-east-1
2020/12/28 15:58:59 DEBUG: Request sts/AssumeRoleWithSAML Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.us-east-1.amazonaws.com
...
DEBU[0007] Using session 3QFD, expires in 59m58.959948s
2020/12/28 15:59:01 DEBUG: Request sts/GetCallerIdentity Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.us-east-1.amazonaws.com
...
```

### CODE REVIEW

**Comment by jinoa-fh** [comment]
does documentation need to be updated to allow for overrides of the default value?

**Comment by Tensho** [comment]
This is just a bugfix. I don't think any documentation should be updated.

**Comment by Tensho** [comment]
@nickatsegment Would you mind to check this stuff?

**Comment by nickatsegment** [comment]
I'm on the fence as to whether this sort of thing is really a bugfix or not, but luckily it's super simple so I'm just going to defer that decision and merge with reckless abandon. Must be the 2021 spirit

**Review by nickatsegment — APPROVED** [review]

**Pull request merged**
